# Generated by Django 5.1.4 on 2025-05-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_app', '0002_alter_offerdetail_features_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerdetail',
            name='features',
            field=models.JSONField(default=None),
        ),
        migrations.AlterField(
            model_name='offerdetail',
            name='offer_type',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
