# Generated by Django 5.1.4 on 2025-05-18 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_app', '0002_alter_offerdetail_price_alter_offerdetail_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerdetail',
            name='revisions',
            field=models.IntegerField(default=0),
        ),
    ]
