# Generated by Django 5.1.4 on 2025-05-23 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_app', '0003_alter_offerdetail_features_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerdetail',
            name='offers',
            field=models.ManyToManyField(related_name='offerdetails', to='offer_app.offer'),
        ),
    ]
