# Generated by Django 5.1.4 on 2025-05-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_app', '0003_alter_offerdetail_revisions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerdetail',
            name='delivery_time_in_days',
            field=models.IntegerField(default=0),
        ),
    ]
