# Generated by Django 5.1.4 on 2025-05-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_app', '0004_alter_offerdetail_delivery_time_in_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerdetail',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
