# Generated by Django 5.1.4 on 2025-05-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_app', '0005_alter_offerdetail_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerdetail',
            name='features',
            field=models.JSONField(default=None),
        ),
    ]
