# Generated by Django 5.1.4 on 2025-05-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_app', '0005_remove_offerdetail_offers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Offer', 'verbose_name_plural': 'Offers'},
        ),
        migrations.AlterModelOptions(
            name='offerdetail',
            options={'ordering': ['price'], 'verbose_name': 'Offer Detail', 'verbose_name_plural': 'Offer Details'},
        ),
        migrations.AlterField(
            model_name='offer',
            name='description',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='offer',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='offerdetail',
            name='features',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='offerdetail',
            name='offer_type',
            field=models.CharField(default='Basic', max_length=50),
        ),
        migrations.AlterField(
            model_name='offerdetail',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='offerdetail',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
