# Generated by Django 5.1.4 on 2025-05-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_app', '0006_alter_offerdetail_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerdetail',
            name='offer_type',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
