# Generated by Django 5.1.4 on 2025-05-29 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_app', '0008_alter_offerdetail_revisions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerdetail',
            name='revisions',
            field=models.IntegerField(default=-1),
        ),
    ]
