# Generated by Django 5.1.4 on 2025-05-29 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0002_alter_order_options_alter_order_business_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='revisions',
            field=models.IntegerField(default=-1),
        ),
    ]
