# Generated by Django 5.1.4 on 2025-05-22 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_customuser_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
