# Generated by Django 5.1.4 on 2025-05-26 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='updated_at',
            new_name='uploaded_at',
        ),
    ]
