# Generated by Django 5.1.4 on 2025-05-17 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_userprofile_delete_user'),
        ('profile_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('userprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth_app.userprofile')),
                ('username', models.CharField(max_length=150)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('file', models.ImageField(blank=True, upload_to='profiles/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            bases=('auth_app.userprofile',),
        ),
    ]
